Models/DogModel.cs
namespace CutestDogsAdoptionService.Models;

public class DogModel
{
    public int Id { get; set; }
    public string Name { get; set; }

    public int Cuteness { get; set; }

    public string Image { get; set; }

    public string FavFood { get; set; }

    public string FavToy { get; set; }

    public int Temperament { get; set; }

    public bool IsAdopted { get; set; }

}

Models/ErrorViewModel.cs
namespace CutestDogsAdoptionService.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DogsController.cs
using CutestDogsAdoptionService.Models;
using Microsoft.AspNetCore.Mvc;

namespace CutestDogsAdoptionService.Controllers;

public class DogsController : Controller
{
	public static List<DogModel> dogs = new List<DogModel>
	{
	new DogModel{ Id = 1, Name = "Bark Twain", Cuteness = 9, Image = "doggo 1.png", FavFood = "Barkoni", FavToy = "Barkle", Temperament = 7, IsAdopted= false },
	new DogModel{ Id = 2, Name = "Sir Waggington", Cuteness = 8, Image = "doggo 2.png", FavFood = "Pawsta", FavToy = "Fetch Stick", Temperament = 6, IsAdopted= false },
	new DogModel{ Id = 3, Name = "Furball", Cuteness = 6, Image = "doggo 3.png", FavFood = "Bone Appetit", FavToy = "Squeaky Ball", Temperament = 8, IsAdopted= false },
	new DogModel{ Id = 4, Name = "Princess Paws", Cuteness = 10, Image = "doggo 4.png", FavFood = "Royal Canin", FavToy = "Diamond Collar", Temperament = 5, IsAdopted= false },
	new DogModel{ Id = 5, Name = "Biscuit", Cuteness = 7, Image = "doggo 5.png", FavFood = "Pupcakes", FavToy = "Chewy Bone", Temperament = 9, IsAdopted= false },
	new DogModel{ Id = 6, Name = "Daisy", Cuteness = 4, Image = "doggo 6.png", FavFood = "Doggie Delight", FavToy = "Plush Squirrel", Temperament = 3, IsAdopted= false },
	new DogModel{ Id = 7, Name = "Captain Woof", Cuteness = 6, Image = "doggo 7.png", FavFood = "Fish 'n Chips", FavToy = "Nautical Rope", Temperament = 8, IsAdopted= false },
	new DogModel{ Id = 8, Name = "Snuggle Paws", Cuteness = 9, Image = "doggo 8.png", FavFood = "Cuddle Crunchies", FavToy = "Soft Blanket", Temperament = 7, IsAdopted= false },
	new DogModel{ Id = 9, Name = "Rocky", Cuteness = 3, Image = "doggo 9.png", FavFood = "Steak Bites", FavToy = "Tennis Ball", Temperament = 4, IsAdopted= false },
	new DogModel{ Id = 10, Name = "Lola", Cuteness = 5, Image = "doggo 10.png", FavFood = "Treat Tower", FavToy = "Squeaky Duck", Temperament = 6, IsAdopted= false },
	new DogModel{ Id = 11, Name = "Maximus", Cuteness = 8, Image = "doggo 11.png", FavFood = "Beefy Bites", FavToy = "Tug Rope", Temperament = 9, IsAdopted= false },
	new DogModel{ Id = 12, Name = "Roxy", Cuteness = 7, Image = "doggo 12.png", FavFood = "Chicken Chewies", FavToy = "Frisbee", Temperament = 4, IsAdopted = false },
	new DogModel{ Id = 13, Name = "Teddy", Cuteness = 2, Image = "doggo 13.png", FavFood = "Carrot Crunch", FavToy = "Plush Bunny", Temperament = 2, IsAdopted = false },
	new DogModel{ Id = 14, Name = "Coco", Cuteness = 6, Image = "doggo 14.png", FavFood = "Coconut Chew", FavToy = "Ball Launcher", Temperament = 8, IsAdopted= false }
	};
	public IActionResult Index()
	{
		List<DogModel> sortetDogs = dogs.OrderBy(d => d.Name).ToList();

		// Visa en view med alla dogs
		return View(sortetDogs);

	}

	public IActionResult Details(int id)
	{
		// hämta hunden med specifikt Id
		DogModel? selectedDog = dogs.FirstOrDefault(d => d.Id == id);

		// skicka den till Viewen.
		return View(selectedDog);
	}

	public IActionResult Adopt(int id)
	{
		// hämta hunden med specifikt Id
		DogModel? selectedDog = dogs.FirstOrDefault(d => d.Id == id);

		// Gör så att selectedDog blir true.
		if (selectedDog != null)
		{
			selectedDog.IsAdopted = true;
		}

		// skicka den till Viewen.
		return View(selectedDog);
	}


}

Controllers/HomeController.cs
using System.Diagnostics;
using CutestDogsAdoptionService.Models;
using Microsoft.AspNetCore.Mvc;

namespace CutestDogsAdoptionService.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Dogs/Adopt.cshtml
@model DogModel


@if(Model == null)
{
	<h1>Could not find dog.</h1>
}
else
{
	<img src="~/images/@Model.Image" />
	<h1>Thank you for adopting this dog</h1>

}

<a asp-controller="Dogs" asp-action="Index">Back to all dogs.</a>

Views/Dogs/Details.cshtml
@model DogModel


@if(Model == null)
{
	<h1>Dog not found</h1>
}
else
{
	<img src="~/images/@Model.Image" style="width: 200px"/>
	

	<div><label>Name: <span>@Model.Name</span></label></div>
	<div><label>Favorite Food: <span>@Model.FavFood</span></label></div>
	<div><label>Favorite Toy: <span>@Model.FavToy</span></label></div>
	<div><label>Temperament: <span>@Model.Temperament</span></label></div>
	<div><label>Cuteness: <span>@Model.Cuteness</span></label></div>
	@if (Model.IsAdopted)
	{
		<h3>This dog found a happy home</h3>
	}
	else
	{
		<br />
		<a class="btn btn-primary" asp-controller="Dogs" asp-action="Adopt" asp-route-id="@Model.Id">Adopt Dog</a>
	}

}
<a asp-controller="Dogs" asp-action="Index">Back to all dogs.</a>

Views/Dogs/Index.cshtml
@model List<DogModel>


@if(Model == null || !Model.Any())
{
	<h1> Could not find Doggos</h1>
}
else
{
	<h1>Our dogs</h1>
	
	@foreach(var dog in Model)
	{
		<div class="dog-item">
			<a asp-controller="Dogs" asp-action="Details" asp-route-id="@dog.Id" ><h2>@dog.Name</h2></a>
			<label>Favorite food: </label>
			<span>@dog.FavFood </span>
			
			för att visa enskil dog.
			@if(dog.IsAdopted) 
			{
				<h3>This dog found a happy home</h3>
			}
			else
			{
				<br />
				<a class="btn btn -primary" asp-controller="Dogs" asp-action="Adopt" asp-route-id="@dog.Id" >Adopt Dog</a>
			}

			<hr />

		</div>
	}

}

Views/Home/Index.cshtml
<a asp-controller="Dogs" asp-action="Index">Our dogs</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CutestDogsAdoptionService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CutestDogsAdoptionService.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CutestDogsAdoptionService</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CutestDogsAdoptionService - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>